BWA_INDEX: /gpfs/data/petljaklab/resources/hg38/pipeline_resources/genome/bwa/hg38.fa
SAMPLES_JSON: 'snakemake_pipeline/samples.json'
FASTQ_FOLDER: '/gpfs/data/petljaklab/data/external_data/raw_sequencing_archive/MPP000012/01.RawData'
WORKING_FOLDER: '/gpfs/data/petljaklab/data/nanoseq'
NORM_FOLDER: '/gpfs/home/okafoa01/udseq_nanoseq_pipeline_032025/data'
PYTHON_FOLDER: '/gpfs/home/okafoa01/NanoSeq/python'
BWA_FOLDER: /gpfs/data/petljaklab/resources/hg38/pipeline_resources/genome/bwa
